#!/usr/bin/guile-2.2 \
-e main -s
!#
;; workaround:
;; -e (@ (sh anguish) main) -s
;; leads to:
;; ERROR: In procedure read:
;; ERROR: In procedure scm_i_lreadparen: #<unknown port>:1:3: end of file

(define (main args)
  (set! %load-path (cons (dirname (car args)) %load-path))
  ((@ (sh anguish) main) args))
