#!/bin/sh

cd oil
export OSH_LIST=bin/geesh

test_name=$(basename "$1")
test_name=${test_name%.sh}
test_name=${test_name%.test}

# This just makes sure that Python 2 produces UTF-8 output when
# redirected to a file (as in the case of our test harness).  There is
# a specific issue that this resolves.  Guile sometimes prints
# ellipses as part of its stack traces.  If Python 2 thinks that it
# should only write ASCII to files, it will throw an error when it
# sees an ellipsis.
export PYTHONIOENCODING=utf-8

./test/spec.sh "$test_name" --verbose
